name: "Pipeline"

on:
    push:
        branches:
            - "master"

jobs:

    call-workflow-passing-data:
        uses: bryanus1/pipelines-reusable/.github/workflows/front_s3.yaml@main
        with:
          bucket_name: "s3-bucket-braves"
        secrets:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
